STRINGS = GLOBAL.STRINGS
if STRINGS.DOTA == nil then
	STRINGS.DOTA = {}
end
--鼠标悬停制作站图标时展现文字
STRINGS.UI.CRAFTING_FILTERS["DOTASHOP"] = "Dota2 商店"
-- STRINGS.UI.CRAFTING_STATION_FILTERS.DOTASHOP = "Dota2 Shop"

--------------------------------------------------------------------------------------------------
-------------------------------------------装备描述------------------------------------------------
--------------------------------------------------------------------------------------------------
--装备栏
STRINGS.NAMES.DOTA_BOX = "装备栏" -- 物体在游戏中显示的名字
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_BOX = "里面可以放下各种形形色色的装备" -- 物体的检查描述
STRINGS.RECIPE_DESC.DOTA_BOX = "开始你的dota之旅" -- 物体的制作栏描述

-------------------------------------------消耗品------------------------------------------------
-- 回城卷轴
STRINGS.NAMES.DOTA_TOWN_PORTAL_SCROLL = "回城卷轴"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_TOWN_PORTAL_SCROLL = "英雄真正需要的东西"
STRINGS.RECIPE_DESC.DOTA_TOWN_PORTAL_SCROLL = "传送"
-- 净化药水 or 小蓝
STRINGS.NAMES.DOTA_CLARITY = "净化药水"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_CLARITY = "能增强冥想能力的清水"
STRINGS.RECIPE_DESC.DOTA_CLARITY = "回蓝药剂"
-- 仙灵之火
STRINGS.NAMES.DOTA_FAERIE_FIRE = "仙灵之火"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_FAERIE_FIRE = "虚无的火焰，来自天木熊熊燃烧的遗迹，可以跨越现实燃烧"
STRINGS.RECIPE_DESC.DOTA_FAERIE_FIRE = "瞬间回血"
-- 侦查守卫
STRINGS.NAMES.DOTA_OBSERVER_WARD = "侦查守卫"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_OBSERVER_WARD = "一种植物形态，只有一半的感知力，一般由巫师学徒培养"
STRINGS.RECIPE_DESC.DOTA_OBSERVER_WARD = "月眼守卫"
-- 岗哨守卫
STRINGS.NAMES.DOTA_SENTRY_WARD = "岗哨守卫"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_SENTRY_WARD = "一种植物形态，原种于一位害世国王的花园中"
STRINGS.RECIPE_DESC.DOTA_SENTRY_WARD = "月眼守卫"
-- 诡计之雾
STRINGS.NAMES.DOTA_SMOKE_OF_DECEIT = "诡计之雾"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_SMOKE_OF_DECEIT = "招摇撞骗的法师梅丁对奥术唯一真正的贡献"
STRINGS.RECIPE_DESC.DOTA_SMOKE_OF_DECEIT = "开雾"
-- 阿哈利姆魔晶
STRINGS.NAMES.DOTA_AGHANIMS_SHARD = "阿哈利姆魔晶"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_AGHANIMS_SHARD = "这块不可思议的水晶只有一名巫师知晓它的起源，而水晶的碎片几乎与赫赫有名的神杖一样让人梦寐以求"
STRINGS.RECIPE_DESC.DOTA_AGHANIMS_SHARD = "制作中"
-- 魔法芒果
STRINGS.NAMES.DOTA_ENCHANTED_MANGO = "魔法芒果"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_ENCHANTED_MANGO = "基迪岛上特有的苦甜参半风味让两栖动物无法抗拒"
STRINGS.RECIPE_DESC.DOTA_ENCHANTED_MANGO = "芒果侠"
-- 魔瓶 or 瓶子
STRINGS.NAMES.DOTA_BOTTLE = "魔瓶"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_BOTTLE = "一个流传至今的古老瓶子，内部空间随着时间的流逝逐渐拥有魔力"
STRINGS.RECIPE_DESC.DOTA_BOTTLE = "寻找域外人士补充"
-- 树之祭祀 or 吃树
STRINGS.NAMES.DOTA_TANGO = "树之祭祀"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_TANGO = "战场上的救命稻草"
STRINGS.RECIPE_DESC.DOTA_TANGO = "吃树"
-- 显影之尘 or 粉
STRINGS.NAMES.DOTA_DUST_OF_APPEARANCE = "显影之尘"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_DUST_OF_APPEARANCE = "容颜易藏，音声难隐"
STRINGS.RECIPE_DESC.DOTA_DUST_OF_APPEARANCE = "粉"
-- 知识之书
STRINGS.NAMES.DOTA_TOME_OF_KNOWLEDGE = "知识之书"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_TOME_OF_KNOWLEDGE = "让兽变成人，人变成神的东西"
STRINGS.RECIPE_DESC.DOTA_TOME_OF_KNOWLEDGE = "书"
-- 治疗药膏
STRINGS.NAMES.DOTA_HEALING_SALVE = "治疗药膏"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_HEALING_SALVE = "即使最严重的伤口也能快速治愈的魔法药膏"
STRINGS.RECIPE_DESC.DOTA_HEALING_SALVE = "大药"
-- 血腥榴弹
STRINGS.NAMES.DOTA_BLOOD_GRENADE = "血腥榴弹"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_BLOOD_GRENADE = "血腥榴弹"
STRINGS.RECIPE_DESC.DOTA_BLOOD_GRENADE = "榴弹"
-------------------------------------------属性--------------------------------------------------
-- 法师长袍
STRINGS.NAMES.DOTA_ROBE_OF_THE_MAGI = "法师长袍"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_ROBE_OF_THE_MAGI = "这个长袍将腐化使用者的灵魂，并以给予智慧作为交换"
STRINGS.RECIPE_DESC.DOTA_ROBE_OF_THE_MAGI = "智力"
-- 欢欣之刃
STRINGS.NAMES.DOTA_BLADE_OF_ALACRITY = "欢欣之刃"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_BLADE_OF_ALACRITY = "一把充满时间魔法的长刃"
STRINGS.RECIPE_DESC.DOTA_BLADE_OF_ALACRITY = "敏捷"
-- 精灵布带
STRINGS.NAMES.DOTA_BAND_OF_ELVENSKIN = "精灵布带"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_BAND_OF_ELVENSKIN = "轻巧且便于行动的柔韧纺织物"
STRINGS.RECIPE_DESC.DOTA_BAND_OF_ELVENSKIN = "敏捷"
-- 力量手套
STRINGS.NAMES.DOTA_GAUNTLETS_OF_STRENGTH = "力量手套"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_GAUNTLETS_OF_STRENGTH = "带来野兽般力量的钉饰皮革手套"
STRINGS.RECIPE_DESC.DOTA_GAUNTLETS_OF_STRENGTH = "力量"
-- 力量腰带
STRINGS.NAMES.DOTA_BELT_OF_STRENGTH = "力量腰带"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_BELT_OF_STRENGTH = "提高活力的重要配件"
STRINGS.RECIPE_DESC.DOTA_BELT_OF_STRENGTH = "力量"
-- 敏捷便鞋
STRINGS.NAMES.DOTA_SLIPPERS_OF_AGILITY = "敏捷便鞋"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_SLIPPERS_OF_AGILITY = "蜘蛛皮做成的轻便靴子，能让你感觉到刺痛"
STRINGS.RECIPE_DESC.DOTA_SLIPPERS_OF_AGILITY = "敏捷"
-- 魔力法杖
STRINGS.NAMES.DOTA_STAFF_OF_WIZARDRY = "魔力法杖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_STAFF_OF_WIZARDRY = "一个由法师长老代代相传的魔法之杖"
STRINGS.RECIPE_DESC.DOTA_STAFF_OF_WIZARDRY = "智力"
-- 食人魔之斧
STRINGS.NAMES.DOTA_OGRE_AXE = "食人魔之斧"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_OGRE_AXE = "只要双手握着就会变得强壮"
STRINGS.RECIPE_DESC.DOTA_OGRE_AXE = "力量"
-- 铁树枝干
STRINGS.NAMES.DOTA_IRON_BRANCH = "铁树枝干"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_IRON_BRANCH = "一根看起来很普通的树枝，它如铁般坚硬的品质赋予持有者好运"
STRINGS.RECIPE_DESC.DOTA_IRON_BRANCH = "全属性"
-- 王冠
STRINGS.NAMES.DOTA_CROWN = "王冠"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_CROWN = "一顶庄严的王冠，打造的目的是保证善良而无能的继承人可以抵御篡夺者，并以铁腕手段治理国事"
STRINGS.RECIPE_DESC.DOTA_CROWN = "全属性"
-- 圆环
STRINGS.NAMES.DOTA_CIRCLET = "圆环"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_CIRCLET = "为人类公主们设计的雅致头环"
STRINGS.RECIPE_DESC.DOTA_CIRCLET = "全属性"
-- 智力斗篷
STRINGS.NAMES.DOTA_MANTLE_OF_INTELLIGENCE = "智力斗篷"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_MANTLE_OF_INTELLIGENCE = "历代女王都穿过的美丽斗篷，上面镶有蓝宝石"
STRINGS.RECIPE_DESC.DOTA_MANTLE_OF_INTELLIGENCE = "智力"
-- 宝冕
STRINGS.NAMES.DOTA_DIADEM = "宝冕"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_DIADEM = "Null"
STRINGS.RECIPE_DESC.DOTA_DIADEM = "全属性"
-------------------------------------------装备--------------------------------------------------
--  标枪
STRINGS.NAMES.DOTA_JAVELIN = "标枪"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_JAVELIN = "一把相当有特色的长矛，攻击时偶尔会刺穿敌人的盔甲"
STRINGS.RECIPE_DESC.DOTA_JAVELIN = "克敌击先"
--  淬毒之珠 or 毒球
STRINGS.NAMES.DOTA_ORB_OF_VENOM = "淬毒之珠"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_ORB_OF_VENOM = "给你的毒器渡上毒蛇的毒液"
STRINGS.RECIPE_DESC.DOTA_ORB_OF_VENOM = "毒球"
--  大剑
STRINGS.NAMES.DOTA_CLAYMORE = "大剑"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_CLAYMORE = "一把能劈透铠甲的剑，通常是新晋剑士的首选武器"
STRINGS.RECIPE_DESC.DOTA_CLAYMORE = "攻击力"
--  短棍
STRINGS.NAMES.DOTA_QUARTERSTAFF = "短棍"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_QUARTERSTAFF = "能让你攻击变快的普通棍子"
STRINGS.RECIPE_DESC.DOTA_QUARTERSTAFF = "攻击力"
--  攻击之爪
STRINGS.NAMES.DOTA_BLADES_OF_ATTACK = "攻击之爪"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_BLADES_OF_ATTACK = "里面藏着的小尖刃不容小觑"
STRINGS.RECIPE_DESC.DOTA_BLADES_OF_ATTACK = "攻击力"
--  加速手套
STRINGS.NAMES.DOTA_GLOVES_OF_HASTE = "加速手套"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_GLOVES_OF_HASTE = "一双似乎能化手中武器为无物的魔法手套"
STRINGS.RECIPE_DESC.DOTA_GLOVES_OF_HASTE = "攻速"
--  枯萎之石
STRINGS.NAMES.DOTA_BLIGHT_STONE = "枯萎之石"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_BLIGHT_STONE = "一颗让人闻风丧胆的石头，发掘自戮尽之地"
STRINGS.RECIPE_DESC.DOTA_BLIGHT_STONE = "减甲球"
--  阔剑
STRINGS.NAMES.DOTA_BROADSWORD = "阔剑"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_BROADSWORD = "骑士经典的武器选择，这把坚固的利刃用于杀敌相当可靠"
STRINGS.RECIPE_DESC.DOTA_BROADSWORD = "攻击力"
--  秘银锤
STRINGS.NAMES.DOTA_MITHRIL_HAMMER = "秘银锤"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_MITHRIL_HAMMER = "由纯粹的秘银打造而成的锤子"
STRINGS.RECIPE_DESC.DOTA_MITHRIL_HAMMER = "攻击力"
--  凝魂之露
STRINGS.NAMES.DOTA_INFUSED_RAINDROP = "凝魂之露"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_INFUSED_RAINDROP = "为魔法突袭提供质朴的防护"
STRINGS.RECIPE_DESC.DOTA_INFUSED_RAINDROP = "魂泪"
--  闪电指套
STRINGS.NAMES.DOTA_BLITZ_KNUCKLES = "闪电指套"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_BLITZ_KNUCKLES = "在地下活动的秘术师对经典非法勾当的再度演绎"
STRINGS.RECIPE_DESC.DOTA_BLITZ_KNUCKLES = "攻速"
--  守护指环
STRINGS.NAMES.DOTA_RING_OF_PROTECTION = "守护指环"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_RING_OF_PROTECTION = "能保护佩戴者的闪光戒指"
STRINGS.RECIPE_DESC.DOTA_RING_OF_PROTECTION = "护甲"
--  锁子甲
STRINGS.NAMES.DOTA_CHAINMAIL = "锁子甲"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_CHAINMAIL = "金属锁链制成的编织甲"
STRINGS.RECIPE_DESC.DOTA_CHAINMAIL = "护甲"
--  铁意头盔
STRINGS.NAMES.DOTA_HELM_OF_IRON_WILL = "铁意头盔"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_HELM_OF_IRON_WILL = "一位战死沙场的传奇战士身故时戴着的头盔"
STRINGS.RECIPE_DESC.DOTA_HELM_OF_IRON_WILL = "护甲"
--  压制之刃 or 补刀斧
STRINGS.NAMES.DOTA_QUELLING_BLADE = "压制之刃"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_QUELLING_BLADE = "堕落地精的斧头，能让你更快的在森林中穿行"
STRINGS.RECIPE_DESC.DOTA_QUELLING_BLADE = "补刀斧"
-------------------------------------------其他--------------------------------------------------
-- 暗影护符
STRINGS.NAMES.DOTA_SHADOW_AMULET = "暗影护符"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_SHADOW_AMULET = "一件小小的护符，握住了完全不动就能隔开敌人的感应"
STRINGS.RECIPE_DESC.DOTA_SHADOW_AMULET = "原地隐身"
-- 风灵之纹
STRINGS.NAMES.DOTA_WIND_LACE = "风灵之纹"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_WIND_LACE = "脚跟经过轻风的吹拂，在战斗中更加轻盈"
STRINGS.RECIPE_DESC.DOTA_WIND_LACE = "移速"
-- 回复戒指
STRINGS.NAMES.DOTA_RING_OF_REGEN = "回复戒指"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_RING_OF_REGEN = "一些侏儒迷信这个戒指能带来好运气"
STRINGS.RECIPE_DESC.DOTA_RING_OF_REGEN = "生命回复"
-- 抗魔斗篷
STRINGS.NAMES.DOTA_CLOAK = "抗魔斗篷"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_CLOAK = "一顶用魔法材料制成的斗篷，可以驱散一切施加于其上的魔法"
STRINGS.RECIPE_DESC.DOTA_CLOAK = "魔抗"
-- 毛毛帽
STRINGS.NAMES.DOTA_FLUFFY_HAT = "毛毛帽"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_FLUFFY_HAT = "缤纷纨绔绒，纯绚绵绝缎"
STRINGS.RECIPE_DESC.DOTA_FLUFFY_HAT = "生命"
-- 魔棒
STRINGS.NAMES.DOTA_MAGIC_STICK = "魔棒"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_MAGIC_STICK = "一根朴实的魔杖，能够引导魔法能量——巫师学徒和高级术士都对其青睐有加"
STRINGS.RECIPE_DESC.DOTA_MAGIC_STICK = "使用魔法来补充能量"
-- 闪烁匕首 or 跳刀
STRINGS.NAMES.DOTA_BLINK_DAGGER = "闪烁匕首"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_BLINK_DAGGER = "科勒的匕首可以让他在任何危险的情况下逃脱"
STRINGS.RECIPE_DESC.DOTA_BLINK_DAGGER = "Blinnnnnk!"
-- 速度之靴 or 鞋子
STRINGS.NAMES.DOTA_BOOTS_OF_SPEED = "速度之靴"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_BOOTS_OF_SPEED = "穿双鞋子，跑的更快"
STRINGS.RECIPE_DESC.DOTA_BOOTS_OF_SPEED = "移速"
-- 巫毒面具
STRINGS.NAMES.DOTA_VOODOO_MASK = "巫毒面具"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_VOODOO_MASK = "一副面具，适合从施法者和敌人之间的奥术维系里吸收少许"
STRINGS.RECIPE_DESC.DOTA_VOODOO_MASK = "法术吸血"
-- 吸血面具
STRINGS.NAMES.DOTA_MORBID_MASK = "吸血面具"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_MORBID_MASK = "这个面具会吸取被它凝视之人的生命力"
STRINGS.RECIPE_DESC.DOTA_MORBID_MASK = "攻击吸血"
-- 贤者面罩
STRINGS.NAMES.DOTA_SAGES_MASK = "贤者面罩"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_SAGES_MASK = "法师和术士在各类祭祀中常用的面罩"
STRINGS.RECIPE_DESC.DOTA_SAGES_MASK = "魔法恢复"
-- 幽魂权杖
STRINGS.NAMES.DOTA_GHOST_SCEPTER = "幽魂权杖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_GHOST_SCEPTER = "赐予使用者幽灵般的姿态，让他们避开物理性的伤害"
STRINGS.RECIPE_DESC.DOTA_GHOST_SCEPTER = "进入虚灵状态"
-- 真视宝石
STRINGS.NAMES.DOTA_GEM_OF_TRUE_SIGHT = "真视宝石"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_GEM_OF_TRUE_SIGHT = "只为苍生不受深海的奴役\n只为生魂免去溺灵要塞的灾戾\n只为让麦尔朗恩长眠于海底\n璀璨的宝石终归于沉寂"
STRINGS.RECIPE_DESC.DOTA_GEM_OF_TRUE_SIGHT = "穿透隐身的纺纱 制作中"
-------------------------------------------神秘商店----------------------------------------------
-- 板甲
STRINGS.NAMES.DOTA_PLATEMAIL = "板甲"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_PLATEMAIL = "保护整个上身的厚重金属板。注意别砸到脚"
STRINGS.RECIPE_DESC.DOTA_PLATEMAIL = "护甲"
-- 恶魔刀锋
STRINGS.NAMES.DOTA_DEMON_EDGE = "恶魔刀锋"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_DEMON_EDGE = "由恶魔铁匠阿布兹迪安锻造的古老武器之一，一出炉就在试刃时杀死了它的锻造者"
STRINGS.RECIPE_DESC.DOTA_DEMON_EDGE = "攻击力"
-- 活力之球
STRINGS.NAMES.DOTA_VITALITY_BOOSTER = "活力之球"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_VITALITY_BOOSTER = "一块在战士家族中世代相传的红宝石"
STRINGS.RECIPE_DESC.DOTA_VITALITY_BOOSTER = "生命"
-- 精气之球
STRINGS.NAMES.DOTA_POINT_BOOSTER = "精气之球"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_POINT_BOOSTER = "一块完美成型的紫水晶，持有时可以滋养身体和心灵"
STRINGS.RECIPE_DESC.DOTA_POINT_BOOSTER = "生命"
-- 能量之球
STRINGS.NAMES.DOTA_ENERGY_BOOSTER = "能量之球"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_ENERGY_BOOSTER = "巫师们若想提升战场上的存在感，通常会把这块天青石加入自己的收藏"
STRINGS.RECIPE_DESC.DOTA_ENERGY_BOOSTER = "魔法"
-- 极限法球
STRINGS.NAMES.DOTA_ULTIMATE_ORB = "极限法球"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_ULTIMATE_ORB = "蕴含生命本质的神秘法球"
STRINGS.RECIPE_DESC.DOTA_ULTIMATE_ORB = "全属性"
-- 掠夺者之斧
STRINGS.NAMES.DOTA_REAVER = "掠夺者之斧"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_REAVER = "一把开山断岳的强力巨斧"
STRINGS.RECIPE_DESC.DOTA_REAVER = "力量"
-- 闪避护符
STRINGS.NAMES.DOTA_TALISMAN_OF_EVASION = "闪避护符"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_TALISMAN_OF_EVASION = "能让你预知到敌人攻击的项链"
STRINGS.RECIPE_DESC.DOTA_TALISMAN_OF_EVASION = "闪避"
-- 神秘法杖
STRINGS.NAMES.DOTA_MYSTIC_STAFF = "神秘法杖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_MYSTIC_STAFF = "这根谜一般的法杖是由最贵重的水晶做成的"
STRINGS.RECIPE_DESC.DOTA_MYSTIC_STAFF = "智力"
-- 圣者遗物
STRINGS.NAMES.DOTA_SACRED_RELIC = "圣者遗物"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_SACRED_RELIC = "一件足以改变战争形势的强力武器"
STRINGS.RECIPE_DESC.DOTA_SACRED_RELIC = "攻击力"
-- 虚无宝石
STRINGS.NAMES.DOTA_VOID_STONE = "虚无宝石"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_VOID_STONE = "一件曾被用来引导冥界魔法的珠宝，这个戒指中跃动着魔力"
STRINGS.RECIPE_DESC.DOTA_VOID_STONE = "魔法恢复"
-- 治疗指环
STRINGS.NAMES.DOTA_RING_OF_HEALTH = "治疗指环"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_RING_OF_HEALTH = "一枚闪闪发光的指环，在一个胖乎乎的半身人尸体下被人所发现"
STRINGS.RECIPE_DESC.DOTA_RING_OF_HEALTH = "生命恢复"
-- 鹰歌弓
STRINGS.NAMES.DOTA_EAGLESONG = "鹰歌弓"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_EAGLESONG = "这只神秘的号角捕获了雄鹰嘹亮的呼啸，能给予听见这声音的英雄几近无限的敏捷度"
STRINGS.RECIPE_DESC.DOTA_EAGLESONG = "敏捷"
-- 振奋宝石
STRINGS.NAMES.DOTA_HYPERSTONE = "振奋宝石"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_HYPERSTONE = "一块刻有神秘纹路的石头，能够提升携带者的激情"
STRINGS.RECIPE_DESC.DOTA_HYPERSTONE = "攻速"
-- 丰饶之环
STRINGS.NAMES.DOTA_HYPERSTONE = "丰饶之环"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_HYPERSTONE = "Null"
STRINGS.RECIPE_DESC.DOTA_HYPERSTONE = "回复"
-------------------------------------------配件--------------------------------------------------
-- 动力鞋 or 假腿
STRINGS.NAMES.DOTA_POWER_TREADS = "动力鞋"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_POWER_TREADS = "一双厚实的皮靴，能根据穿着者的需求切换属性"
STRINGS.RECIPE_DESC.DOTA_POWER_TREADS = "攻速"
-- 疯狂面具
STRINGS.NAMES.DOTA_MASK_OF_MADNESS = "疯狂面具"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_MASK_OF_MADNESS = "一旦戴上这个面具就会变成无法控制的好战分子"
STRINGS.RECIPE_DESC.DOTA_MASK_OF_MADNESS = "攻速"
-- 腐蚀之球
STRINGS.NAMES.DOTA_ORB_OF_CORROSION = "腐蚀之球"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_ORB_OF_CORROSION = "凶残的屠杀战役过后，从战士之神的伤口渗出的液体被封进一个秘术师的宝珠内"
STRINGS.RECIPE_DESC.DOTA_ORB_OF_CORROSION = "基础物品"
-- 护腕
STRINGS.NAMES.DOTA_BRACER = "护腕"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_BRACER = "护腕是增强防御、延长寿命的常见选择"
STRINGS.RECIPE_DESC.DOTA_BRACER = "力量"
-- 坚韧球
STRINGS.NAMES.DOTA_PERSEVERANCE = "坚韧球"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_PERSEVERANCE = "给持有者带来勇气的宝石"
STRINGS.RECIPE_DESC.DOTA_PERSEVERANCE = "生命回复"
-- 空灵挂件
STRINGS.NAMES.DOTA_NULL_TALISMAN = "空灵挂件"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_NULL_TALISMAN = "由锁链装饰起来的小巧的宝石"
STRINGS.RECIPE_DESC.DOTA_NULL_TALISMAN = "智力"
-- 空明杖
STRINGS.NAMES.DOTA_OBLIVION_STAFF = "空明杖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_OBLIVION_STAFF = "让人误以为只是根普通战棍的外表下，其实威力不凡，就像原来拥有它的邪王"
STRINGS.RECIPE_DESC.DOTA_OBLIVION_STAFF = "攻击力"
-- 猎鹰战刃
STRINGS.NAMES.DOTA_FALCON_BLADE = "猎鹰战刃"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_FALCON_BLADE = "一把具有魔力的战刃，多年前让一个无可救药的顽童从乞丐登上王位"
STRINGS.RECIPE_DESC.DOTA_FALCON_BLADE = "攻击力"
-- 灵魂之戒
STRINGS.NAMES.DOTA_SOUL_RING = "灵魂之戒"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_SOUL_RING = "一枚能吞噬佩带者灵魂的戒指"
STRINGS.RECIPE_DESC.DOTA_SOUL_RING = "魔法"
-- 迈达斯之手 or 点金手
STRINGS.NAMES.DOTA_HAND_OF_MIDAS = "迈达斯之手"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_HAND_OF_MIDAS = "以未知的魔法手段维持着的迈达斯之手，是件贪婪的武器，通过炼化生灵来装满持有者的腰包"
STRINGS.RECIPE_DESC.DOTA_HAND_OF_MIDAS = "点金手"
-- 魔杖
STRINGS.NAMES.DOTA_MAGIC_WAND = "魔杖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_MAGIC_WAND = "一根朴实的魔杖，能够引导魔法能量——巫师学徒和高级术士都对其青睐有加"
STRINGS.RECIPE_DESC.DOTA_MAGIC_WAND = "使用魔法来补充能量"
-- 统御头盔
STRINGS.NAMES.DOTA_HELM_OF_THE_OVERLORD = "统御头盔"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_HELM_OF_THE_OVERLORD = "死去的死灵法师留下的强大头盔"
STRINGS.RECIPE_DESC.DOTA_HELM_OF_THE_OVERLORD = "支配"
-- 相位鞋
STRINGS.NAMES.DOTA_PHASE_BOOTS = "相位鞋"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_PHASE_BOOTS = "穿着它的人可以穿越虚空"
STRINGS.RECIPE_DESC.DOTA_PHASE_BOOTS = "移速"
-- 银月之晶
STRINGS.NAMES.DOTA_MOON_SHARD = "银月之晶"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_MOON_SHARD = "相传这是月之女神赛莉蒙妮流下的一滴眼泪"
STRINGS.RECIPE_DESC.DOTA_MOON_SHARD = "攻速"
-- 远行鞋I or 飞鞋
STRINGS.NAMES.DOTA_BOOTS_OF_TRAVEL_LEVEL1 = "远行鞋I"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_BOOTS_OF_TRAVEL_LEVEL1 = "足生双翼，上天入地"
STRINGS.RECIPE_DESC.DOTA_BOOTS_OF_TRAVEL_LEVEL1 = "传送"
-- 远行鞋II or 大飞鞋
STRINGS.NAMES.DOTA_BOOTS_OF_TRAVEL_LEVEL2 = "远行鞋II"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_BOOTS_OF_TRAVEL_LEVEL2 = "足生双翼，上天入地"
STRINGS.RECIPE_DESC.DOTA_BOOTS_OF_TRAVEL_LEVEL2 = "传送"
-- 怨灵系带
STRINGS.NAMES.DOTA_WRAITH_BAND = "怨灵系带"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_WRAITH_BAND = "总是回响着微弱耳语的圆环"
STRINGS.RECIPE_DESC.DOTA_WRAITH_BAND = "敏捷"
-- 支配头盔
STRINGS.NAMES.DOTA_HELM_OF_THE_DOMINATOR = "支配头盔"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_HELM_OF_THE_DOMINATOR = "死去的死灵法师留下的可怕头盔"
STRINGS.RECIPE_DESC.DOTA_HELM_OF_THE_DOMINATOR = "支配"
-------------------------------------------辅助--------------------------------------------------
-- 奥术鞋 or 秘法鞋
STRINGS.NAMES.DOTA_ARCANE_BOOTS = "奥术鞋"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_ARCANE_BOOTS = "装备这种鞋子的法师在战斗中值得重视"
STRINGS.RECIPE_DESC.DOTA_ARCANE_BOOTS = "魔法"
-- 洞察烟斗  or 笛子
STRINGS.NAMES.DOTA_PIPE_OF_INSIGHT = "洞察烟斗"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_PIPE_OF_INSIGHT = "一件来源神秘的强大古物，能制造出抵挡法术攻击的护盾"
STRINGS.RECIPE_DESC.DOTA_PIPE_OF_INSIGHT = "魔抗"
-- 弗拉迪米尔的祭品
STRINGS.NAMES.DOTA_VLADMIRS_OFFERING = "弗拉迪米尔的祭品"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_VLADMIRS_OFFERING = "一副怪异的面具，纠缠着死去吸血鬼的怨念"
STRINGS.RECIPE_DESC.DOTA_VLADMIRS_OFFERING = "吸血"
-- 恢复头巾
STRINGS.NAMES.DOTA_HEADDRESS = "恢复头巾"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_HEADDRESS = "创造一个镇痛的光环在战斗中为友军恢复生命"
STRINGS.RECIPE_DESC.DOTA_HEADDRESS = "生命恢复"
-- 魂之灵瓮 or 大骨灰
STRINGS.NAMES.DOTA_SPIRIT_VESSEL = "魂之灵瓮"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_SPIRIT_VESSEL = "由一位神铸造，用来俘获同类的灵魂"
STRINGS.RECIPE_DESC.DOTA_SPIRIT_VESSEL = "持续伤害"
-- 影之灵龛 or 骨灰
STRINGS.NAMES.DOTA_URN_OF_SHADOWS = "影之灵龛"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_URN_OF_SHADOWS = "内含强大恶魔的骨灰"
STRINGS.RECIPE_DESC.DOTA_URN_OF_SHADOWS = "持续伤害"
-- 静谧之鞋 or 绿鞋
STRINGS.NAMES.DOTA_TRANQUIL_BOOTS = "静谧之鞋"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_TRANQUIL_BOOTS = "虽然延长了穿戴者的寿命，但这鞋子其实并不可靠"
STRINGS.RECIPE_DESC.DOTA_TRANQUIL_BOOTS = "移速"
-- 宽容之靴 or 大绿鞋
STRINGS.NAMES.DOTA_BOOTS_OF_BEARING = "宽容之靴"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_BOOTS_OF_BEARING = "这双华丽的靴子是为一个古代的先驱打造，是他率先敢于将石堂城的荣光散播到国土的初始边界之外"
STRINGS.RECIPE_DESC.DOTA_BOOTS_OF_BEARING = "移速"
-- 梅肯斯姆
STRINGS.NAMES.DOTA_MEKANSM = "梅肯斯姆"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_MEKANSM = "各种散件不知是怎样完美地组合起来，形成了散发着光芒的珠宝"
STRINGS.RECIPE_DESC.DOTA_MEKANSM = "回血"
-- 韧鼓
STRINGS.NAMES.DOTA_DRUM_OF_ENDURANCE = "韧鼓"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_DRUM_OF_ENDURANCE = "在危难时刻能鼓舞周围人士气的遗物"
STRINGS.RECIPE_DESC.DOTA_DRUM_OF_ENDURANCE = "移速"
-- 圣洁吊坠
STRINGS.NAMES.DOTA_HOLY_LOCKET = "圣洁吊坠"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_HOLY_LOCKET = "一件珍贵的圣物，多年以来人们认为在远征失败后已经永远地遗失了"
STRINGS.RECIPE_DESC.DOTA_HOLY_LOCKET = "治疗你的同伴"
-- 王者之戒
STRINGS.NAMES.DOTA_RING_OF_BASILIUS = "王者之戒"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_RING_OF_BASILIUS = "这枚戒指是最伟大的法师才能获得的嘉奖"
STRINGS.RECIPE_DESC.DOTA_RING_OF_BASILIUS = "魔法恢复"
-- 卫士胫甲 or 大鞋
STRINGS.NAMES.DOTA_GUARDIAN_GREAVES = "卫士胫甲"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_GUARDIAN_GREAVES = "为了向全能之神致敬所打造的众多圣器之一"
STRINGS.RECIPE_DESC.DOTA_GUARDIAN_GREAVES = "回血"
-- 玄冥盾牌
STRINGS.NAMES.DOTA_BUCKLER = "玄冥盾牌"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_BUCKLER = "一面强大的盾牌赐予携带者过往英雄们的力量，它能在战斗中为整支军队提供保护"
STRINGS.RECIPE_DESC.DOTA_BUCKLER = "护甲"
-- 勇气勋章
STRINGS.NAMES.DOTA_MEDALLION_OF_COURAGE = "勇气勋章"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_MEDALLION_OF_COURAGE = "持有者将无惧于战斗"
STRINGS.RECIPE_DESC.DOTA_MEDALLION_OF_COURAGE = "护甲"
-- 怨灵之契
STRINGS.NAMES.DOTA_WRAITH_PACT = "怨灵之契"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_WRAITH_PACT = "有意识的护身符，其中的敌意能让最强大的敌人动摇勇气"
STRINGS.RECIPE_DESC.DOTA_WRAITH_PACT = "召唤猪猪"
-- 长盾
STRINGS.NAMES.DOTA_PAVISE = "长盾"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_PAVISE = "Null"
STRINGS.RECIPE_DESC.DOTA_PAVISE = "护盾"
-------------------------------------------法器--------------------------------------------------
-- 吹风 OR EUL的神圣法杖
STRINGS.NAMES.DOTA_EULS_SCEPTER_OF_DIVINITY = "EUL的神圣法杖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_EULS_SCEPTER_OF_DIVINITY = "一支从久远年代流传下来的神秘权杖，能招来破坏性的龙卷风行善或作恶"
STRINGS.RECIPE_DESC.DOTA_EULS_SCEPTER_OF_DIVINITY = "在天空中飞翔"
-- 阿哈利姆神杖
STRINGS.NAMES.DOTA_AGHANIMS_SCEPTER = "阿哈利姆神杖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_AGHANIMS_SCEPTER = "这把权杖属于拥有半神之力的法师"
STRINGS.RECIPE_DESC.DOTA_AGHANIMS_SCEPTER = "制作中"
-- 阿托斯之棍
STRINGS.NAMES.DOTA_ROD_OF_ATOS = "阿托斯之棍"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_ROD_OF_ATOS = "荒芜之王阿托斯将他的精粹储存在这根看似平平无奇的魔杖中"
STRINGS.RECIPE_DESC.DOTA_ROD_OF_ATOS = "困住你的敌人"
-- 达贡之神力1 OR 大根
STRINGS.NAMES.DOTA_DAGON_LEVEL1 = "达贡之神力Ⅰ"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_DAGON_LEVEL1 = "越用威力就越大的次级法杖，让持有者的魔法从指尖喷涌而出"
STRINGS.RECIPE_DESC.DOTA_DAGON_LEVEL1 = "助攻之神力1"
-- 达贡之神力2 OR 大根
STRINGS.NAMES.DOTA_DAGON_LEVEL2 = "达贡之神力Ⅱ"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_DAGON_LEVEL2 = "越用威力就越大的次级法杖，让持有者的魔法从指尖喷涌而出"
STRINGS.RECIPE_DESC.DOTA_DAGON_LEVEL2 = "助攻之神力2"
-- 达贡之神力3 OR 大根
STRINGS.NAMES.DOTA_DAGON_LEVEL3 = "达贡之神力Ⅲ"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_DAGON_LEVEL3 = "越用威力就越大的次级法杖，让持有者的魔法从指尖喷涌而出"
STRINGS.RECIPE_DESC.DOTA_DAGON_LEVEL3 = "助攻之神力3"
-- 达贡之神力4 OR 大根
STRINGS.NAMES.DOTA_DAGON_LEVEL4 = "达贡之神力Ⅳ"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_DAGON_LEVEL4 = "越用威力就越大的次级法杖，让持有者的魔法从指尖喷涌而出"
STRINGS.RECIPE_DESC.DOTA_DAGON_LEVEL4 = "助攻之神力4"
-- 达贡之神力5 OR 大根
STRINGS.NAMES.DOTA_DAGON_LEVEL5 = "达贡之神力Ⅴ"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_DAGON_LEVEL5 = "越用威力就越大的次级法杖，让持有者的魔法从指尖喷涌而出"
STRINGS.RECIPE_DESC.DOTA_DAGON_LEVEL5 = "助攻之神力5"
-- 纷争面纱
STRINGS.NAMES.DOTA_VEIL_OF_DISCORD = "纷争面纱"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_VEIL_OF_DISCORD = "一个堕落法师的头饰"
STRINGS.RECIPE_DESC.DOTA_VEIL_OF_DISCORD = "制作中"
-- 风之杖 or 大吹风
STRINGS.NAMES.DOTA_WIND_WAKER = "风之杖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_WIND_WAKER = "对于部分人来说，足以证明看不见的势力操控着现实位面发生的事件"
STRINGS.RECIPE_DESC.DOTA_WIND_WAKER = "空中行走"
-- 缚灵索
STRINGS.NAMES.DOTA_GLEIPNIR = "缚灵索"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_GLEIPNIR = "以不可能的手段铸就的束缚之物，为了限制一个上古魔物"
STRINGS.RECIPE_DESC.DOTA_GLEIPNIR = "制作中"
-- 玲珑心
STRINGS.NAMES.DOTA_OCTARINE_CORE = "玲珑心"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_OCTARINE_CORE = "位于法术技艺核心的，是只有身负异能之人才能感知的光带"
STRINGS.RECIPE_DESC.DOTA_OCTARINE_CORE = "减少冷却"
-- 刷新球
STRINGS.NAMES.DOTA_REFRESHER_ORB = "刷新球"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_REFRESHER_ORB = "一件为巫师量身定做的强力物品"
STRINGS.RECIPE_DESC.DOTA_REFRESHER_ORB = "重置冷却"
-- 微光披风
STRINGS.NAMES.DOTA_GLIMMER_CAPE = "微光披风	"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_GLIMMER_CAPE = "一位幻术大师失窃的披风"
STRINGS.RECIPE_DESC.DOTA_GLIMMER_CAPE = "渐隐"
-- 巫师之刃
STRINGS.NAMES.DOTA_WITCH_BLADE = "巫师之刃"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_WITCH_BLADE = "一把怨毒的战刃，它鲁莽的创造者不慎将自己的灵魂依附在上面"
STRINGS.RECIPE_DESC.DOTA_WITCH_BLADE = "攻击力"
-- 邪恶镰刀  or 羊刀
STRINGS.NAMES.DOTA_SCYTHE_OF_VYSE = "邪恶镰刀"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_SCYTHE_OF_VYSE = "维斯教会中守卫最为森严的圣物，也是法师们最为垂涎的武器"
STRINGS.RECIPE_DESC.DOTA_SCYTHE_OF_VYSE = "制作中"
-- 炎阳纹章
STRINGS.NAMES.DOTA_SOLAR_CREST = "炎阳纹章"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_SOLAR_CREST = "为了纪念炎日天空所打造的护符"
STRINGS.RECIPE_DESC.DOTA_SOLAR_CREST = "护甲"
-- 以太透镜
STRINGS.NAMES.DOTA_AETHER_LENS = "以太透镜"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_AETHER_LENS = "这件礼物上点缀着行将就木的法师拼着最后一口气说出的咒语，被赠予他体弱多病的儿子"
STRINGS.RECIPE_DESC.DOTA_AETHER_LENS = "制作中"
-- 原力法杖
STRINGS.NAMES.DOTA_FORCE_STAFF = "原力法杖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_FORCE_STAFF = "让你可以操纵他人，不论出于善或恶"
STRINGS.RECIPE_DESC.DOTA_FORCE_STAFF = "推推"
-- 紫怨
STRINGS.NAMES.DOTA_ORCHID_MALEVOLENCE = "紫怨"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_ORCHID_MALEVOLENCE = "一颗诞自火焰恶魔精华的榴石"
STRINGS.RECIPE_DESC.DOTA_ORCHID_MALEVOLENCE = "延迟伤害"
-------------------------------------------防具--------------------------------------------------
-- 赤红甲
STRINGS.NAMES.DOTA_CRIMSON_GUARD = "赤红甲"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_CRIMSON_GUARD = "原为抵御可怕的年兽所打造的铠甲"
STRINGS.RECIPE_DESC.DOTA_CRIMSON_GUARD = "护甲"
-- 黑黄杖
STRINGS.NAMES.DOTA_BLACK_KING_BAR = "黑黄杖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_BLACK_KING_BAR = "渗透了巨人之力的强大法杖"
STRINGS.RECIPE_DESC.DOTA_BLACK_KING_BAR = "Bkb"
-- 幻影斧 or 分身斧
STRINGS.NAMES.DOTA_MANTA_STYLE = "幻影斧"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_MANTA_STYLE = "用反光材料制成的斧头，能够混淆敌军"
STRINGS.RECIPE_DESC.DOTA_MANTA_STYLE = "制作中"
-- 飓风长戟
STRINGS.NAMES.DOTA_HURRICANE_PIKE = "飓风长戟"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_HURRICANE_PIKE = "一柄传奇战戟，曾是远古飞龙骑士的皇家印记"
STRINGS.RECIPE_DESC.DOTA_HURRICANE_PIKE = "大推推"
-- 恐鳌之心
STRINGS.NAMES.DOTA_HEART_OF_TARRASQUE = "恐鳌之心"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_HEART_OF_TARRASQUE = "保存完好的心脏，来自早已绝种的怪兽，能提升携带者的耐久力"
STRINGS.RECIPE_DESC.DOTA_HEART_OF_TARRASQUE = "生命恢复"
-- 林肯法球
STRINGS.NAMES.DOTA_LINKENS_SPHERE = "林肯法球"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_LINKENS_SPHERE = "这个有魔力的球体曾经保护了一位历史上最有名的英雄"
STRINGS.RECIPE_DESC.DOTA_LINKENS_SPHERE = "制作中"
-- 强袭胸甲
STRINGS.NAMES.DOTA_ASSAULT_CUIRASS = "强袭胸甲"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_ASSAULT_CUIRASS = "在三途川的深处锻造而成，这件地狱盔甲能提高整支军队的护甲和攻击速度"
STRINGS.RECIPE_DESC.DOTA_ASSAULT_CUIRASS = "护甲"
-- 清莲宝珠 or 莲花
STRINGS.NAMES.DOTA_LOTUS_ORB = "清莲宝珠"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_LOTUS_ORB = "位居中央的宝石依然能反射出其制造者苍白的景象"
STRINGS.RECIPE_DESC.DOTA_LOTUS_ORB = "制作中"
-- 刃甲
STRINGS.NAMES.DOTA_BLADE_MAIL = "刃甲"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_BLADE_MAIL = "覆盖着尖锐剃刀的盔甲，战斗中可以用来做出不顾自身安危的烈士行为"
STRINGS.RECIPE_DESC.DOTA_BLADE_MAIL = "反弹伤害"
-- 挑战头巾
STRINGS.NAMES.DOTA_HOOD_OF_DEFIANCE = "挑战头巾"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_HOOD_OF_DEFIANCE = "一件具有魔法抵抗力的皮质头巾，受到巫师们的畏惧"
STRINGS.RECIPE_DESC.DOTA_HOOD_OF_DEFIANCE = "魔抗"
-- 希瓦的守护 or 冰甲
STRINGS.NAMES.DOTA_SHIVAS_GUARD = "希瓦的守护"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_SHIVAS_GUARD = "据说曾经属于某位女神，至今仍保持大部分神力"
STRINGS.RECIPE_DESC.DOTA_SHIVAS_GUARD = "制作中"
-- 先锋盾
STRINGS.NAMES.DOTA_VANGUARD = "先锋盾"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_VANGUARD = "能够让持有者躲过最致命攻击的强力盾牌"
STRINGS.RECIPE_DESC.DOTA_VANGUARD = "护甲"
-- 血精石
STRINGS.NAMES.DOTA_BLOODSTONE = "血精石"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_BLOODSTONE = "血精石鲜红的色彩在战场上绝对不会被看错，拥有者似乎有无限的生命力和精力"
STRINGS.RECIPE_DESC.DOTA_BLOODSTONE = "吸血"
-- 永恒之盘 or 盘子
STRINGS.NAMES.DOTA_AEON_DISK = "永恒之盘"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_AEON_DISK = "一件多年以前被偷偷运出象牙孵巢的强力宝物。很多人都相信了这个说法"
STRINGS.RECIPE_DESC.DOTA_AEON_DISK = "制作中"
-- 永世法衣
STRINGS.NAMES.DOTA_ETERNAL_SHROUD = "永世法衣"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_ETERNAL_SHROUD = "崭新的兜帽，以斗争为能量加强它的主人"
STRINGS.RECIPE_DESC.DOTA_ETERNAL_SHROUD = "抵御魔法伤害"
-- 振魂石
STRINGS.NAMES.DOTA_SOUL_BOOSTER = "振魂石"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_SOUL_BOOSTER = "再次鼓起丧失的勇气"
STRINGS.RECIPE_DESC.DOTA_SOUL_BOOSTER = "属性"
-------------------------------------------兵刃--------------------------------------------------
-- 黯灭
STRINGS.NAMES.DOTA_DESOLATOR = "黯灭"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_DESOLATOR = "这件邪恶并且嗜血的武器，通常用于拷打政治犯"
STRINGS.RECIPE_DESC.DOTA_DESOLATOR = "攻击力"
-- 白银之锋 OR 大隐刀
STRINGS.NAMES.DOTA_SILVER_EDGE = "白银之锋"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_SILVER_EDGE = "曾经是手刃不义之君的利器，但是后来王国也因此陷入了内乱"
STRINGS.RECIPE_DESC.DOTA_SILVER_EDGE = "隐身"
-- 代达罗斯之殇 or 大炮
STRINGS.NAMES.DOTA_DAEDALUS = "代达罗斯之殇"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_DAEDALUS = "这件武器有着惊人的力量，即使是最强的战士也难以掌控它"
STRINGS.RECIPE_DESC.DOTA_DAEDALUS = "暴击"
-- 否决坠饰
STRINGS.NAMES.DOTA_NULLIFIER = "否决坠饰"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_NULLIFIER = "危险的武器，盗自一个反维度"
STRINGS.RECIPE_DESC.DOTA_NULLIFIER = "减速敌人"
-- 蝴蝶
STRINGS.NAMES.DOTA_BUTTERFLY = "蝴蝶"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_BUTTERFLY = "只有最强大最老练的战士才能携带蝴蝶，但它也提供无可比拟的战斗灵活力作为回报"
STRINGS.RECIPE_DESC.DOTA_BUTTERFLY = "蝴蝶振翅，卷起风暴"
-- 辉耀
STRINGS.NAMES.DOTA_RADIANCE = "辉耀"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_RADIANCE = "一把神圣的武器，剑身的耀眼光芒能将敌人化为灰烬"
STRINGS.RECIPE_DESC.DOTA_RADIANCE = "持续伤害"
-- 金箍棒
STRINGS.NAMES.DOTA_MONKEY_KING_BAR = "金箍棒"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_MONKEY_KING_BAR = "一位大师级战士使用的强力棍棒"
STRINGS.RECIPE_DESC.DOTA_MONKEY_KING_BAR = "攻击力"
-- 狂战斧
STRINGS.NAMES.DOTA_BATTLE_FURY = "狂战斧" --  物体在游戏中显示的名字
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_BATTLE_FURY = "持有这把强大斧头的人可以一次砍倒一片敌人" --  物体的检查描述
STRINGS.RECIPE_DESC.DOTA_BATTLE_FURY = "近战不出狂战斧，不如回家卖红薯" --  物体的制作栏描述
-- 莫尔迪基安的臂章
STRINGS.NAMES.DOTA_ARMLET_OF_MORDIGGIAN = "莫尔迪基安的臂章"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_ARMLET_OF_MORDIGGIAN = "暴徒们首选的武器，持有者牺牲自己的生命能量来获得巨大力量"
STRINGS.RECIPE_DESC.DOTA_ARMLET_OF_MORDIGGIAN = "制作中"
-- 深渊之刃 or 大晕
STRINGS.NAMES.DOTA_ABYSSAL_BLADE = "深渊之刃"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_ABYSSAL_BLADE = "深渊指挥官的失落宝剑，能够轻易刺穿敌人的灵魂"
STRINGS.RECIPE_DESC.DOTA_ABYSSAL_BLADE = "制作中"
-- 圣剑
STRINGS.NAMES.DOTA_DIVINE_RAPIER = "圣剑"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_DIVINE_RAPIER = "它强横无匹，并不满足于侍奉唯一的主人"
STRINGS.RECIPE_DESC.DOTA_DIVINE_RAPIER = "攻击力"
-- 水晶剑
STRINGS.NAMES.DOTA_CRYSTALYS = "水晶剑"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_CRYSTALYS = "用稀有水晶锻造的剑刃，会寻找敌人护甲的脆弱处"
STRINGS.RECIPE_DESC.DOTA_CRYSTALYS = "暴击"
-- 碎颅锤 or 晕锤
STRINGS.NAMES.DOTA_SKULL_BASHER = "碎颅锤"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_SKULL_BASHER = "用对了地方会让人闻风丧胆的武器，千万不要低估这把大槌粉碎对手防御的能力"
STRINGS.RECIPE_DESC.DOTA_SKULL_BASHER = "制作中"
-- 虚灵之刃
STRINGS.NAMES.DOTA_ETHEREAL_BLADE = "虚灵之刃"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_ETHEREAL_BLADE = "一把忽隐忽现的阴森刀刃，可以在物理和魔法两个位面造成伤害"
STRINGS.RECIPE_DESC.DOTA_ETHEREAL_BLADE = "让生物进入虚灵状态"
-- 血棘 or 大紫怨
STRINGS.NAMES.DOTA_BLOODTHORN = "血棘"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_BLOODTHORN = "一把亵渎之刃，受害者临死前的每次挣扎都会使其砍得更深"
STRINGS.RECIPE_DESC.DOTA_BLOODTHORN = "延迟伤害"
-- 英灵胸针
STRINGS.NAMES.DOTA_REVENANTS_BROOCH = "英灵胸针"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_REVENANTS_BROOCH = "这枚受到诅咒的胸针属于一位堕落的卫士，她永远都在生死之界徘徊"
STRINGS.RECIPE_DESC.DOTA_REVENANTS_BROOCH = "魔法攻击"
-- 隐刀
STRINGS.NAMES.DOTA_INVIS_SWORD = "隐刀" --  物体在游戏中显示的名字
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_INVIS_SWORD = "一位国王死后留下的宝剑，拿着它你可以隐身移动并从阴影中发动突袭" --  物体的检查描述
STRINGS.RECIPE_DESC.DOTA_INVIS_SWORD = "隐身" --  物体的制作栏描述
-- 陨星锤
STRINGS.NAMES.DOTA_METEOR_HAMMER = "陨星锤"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_METEOR_HAMMER = "一柄带有魔力的战锤，铸造所用的金属发掘自被流星雨摧毁的村庄废墟之内"
STRINGS.RECIPE_DESC.DOTA_METEOR_HAMMER = "一起来看流星雨"
-- 散魂剑
STRINGS.NAMES.DOTA_DISPERSER = "散魂剑"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_DISPERSER = "Null"
STRINGS.RECIPE_DESC.DOTA_DISPERSER = "制作中"
-------------------------------------------宝物--------------------------------------------------
-- 法师克星
STRINGS.NAMES.DOTA_MAGE_SLAYER = "法师克星"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_MAGE_SLAYER = "在天瑶城的第三纪元由一个秘密教团打造，意图扳倒冒牌的大帝"
STRINGS.RECIPE_DESC.DOTA_MAGE_SLAYER = "魔抗"
-- 回音战刃 or 连击刀
STRINGS.NAMES.DOTA_ECHO_SABRE = "回音战刃"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_ECHO_SABRE = "一把看似迅捷异常的战刃，其中注入了共鸣魔力"
STRINGS.RECIPE_DESC.DOTA_ECHO_SABRE = "连击"
-- 斯嘉蒂之眼 or 冰眼
STRINGS.NAMES.DOTA_EYE_OF_SKADI = "斯嘉蒂之眼"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_EYE_OF_SKADI = "极度罕见的古物，由苍空之龙看管"
STRINGS.RECIPE_DESC.DOTA_EYE_OF_SKADI = "属性"
-- 天堂之戟
STRINGS.NAMES.DOTA_HEAVENS_HALBERD = "天堂之戟"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_HEAVENS_HALBERD = "这把战戟挥动起来如同轻型武器般迅捷，能让持有者赢得决斗的胜利"
STRINGS.RECIPE_DESC.DOTA_HEAVENS_HALBERD = "限制敌人的攻击"
-- 魔龙枪
STRINGS.NAMES.DOTA_DRAGON_LANCE = "魔龙枪"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_DRAGON_LANCE = "向前冲锋的飞龙群毫不留情"
STRINGS.RECIPE_DESC.DOTA_DRAGON_LANCE = "攻击距离"
-- 撒旦之邪力 or 大吸
STRINGS.NAMES.DOTA_SATANIC = "撒旦之邪力"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_SATANIC = "无穷的力量，需要你付出灵魂作为代价"
STRINGS.RECIPE_DESC.DOTA_SATANIC = "吸血"
-- 净魂之刃 or 散失
STRINGS.NAMES.DOTA_DIFFUSAL_BLADE = "净魂之刃"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_DIFFUSAL_BLADE = "一把直接切入敌人灵魂的魔力之刃"
STRINGS.RECIPE_DESC.DOTA_DIFFUSAL_BLADE = "减速"
-- 电锤
STRINGS.NAMES.DOTA_MAELSTROM = "漩涡"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_MAELSTROM = "神亲自打造的战锤，漩涡可以在攻击中发动闪电的力量"
STRINGS.RECIPE_DESC.DOTA_MAELSTROM = "攻击力"
-- 雷神之锤 or 大雷锤 or 大电锤
STRINGS.NAMES.DOTA_MJOLLNIR = "雷神之锤"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_MJOLLNIR = "索尔的魔法之锤，由矮人名匠布鲁克和艾崔打造"
STRINGS.RECIPE_DESC.DOTA_MJOLLNIR = "电"
-- 慧光
STRINGS.NAMES.DOTA_KAYA = "慧光"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_KAYA = "一位闻名遐迩的女巫师手上的法杖，已经失落了上万年"
STRINGS.RECIPE_DESC.DOTA_KAYA = "智力"
-- 散华
STRINGS.NAMES.DOTA_SANGE = "散华"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_SANGE = "散华是一把异常精准的武器，会自动寻找对方的弱点所在"
STRINGS.RECIPE_DESC.DOTA_SANGE = "力量"
-- 夜叉
STRINGS.NAMES.DOTA_YASHA = "夜叉"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_YASHA = "夜叉可以称得上有史以来最轻巧的武器"
STRINGS.RECIPE_DESC.DOTA_YASHA = "敏捷"
-- 慧夜对剑
STRINGS.NAMES.DOTA_YASHA_AND_KAYA = "慧夜对剑"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_YASHA_AND_KAYA = "夜叉和慧光配成一对时会产生共鸣"
STRINGS.RECIPE_DESC.DOTA_YASHA_AND_KAYA = "敏捷"
-- 散慧对剑
STRINGS.NAMES.DOTA_KAYA_AND_SANGE = "散慧对剑"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_KAYA_AND_SANGE = "这是三大利器的其中两件，因为他们都蕴含着不可思议的力量，很多人相信他们全是在同一个附魔师的熔炉中打造的"
STRINGS.RECIPE_DESC.DOTA_KAYA_AND_SANGE = "智力"
-- 散夜对剑
STRINGS.NAMES.DOTA_SANGE_AND_YASHA = "散夜对剑"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_SANGE_AND_YASHA = "散华和夜叉经过月光的照耀而产生共鸣，双剑合璧发挥出更大的威力"
STRINGS.RECIPE_DESC.DOTA_SANGE_AND_YASHA = "状态抗性"
-- 迅疾闪光 OR 敏捷跳
STRINGS.NAMES.DOTA_SWIFT_BLINK = "迅疾闪光"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_SWIFT_BLINK = "一把聪颖的战刃，可以预见佩戴者的动向并加以实现"
STRINGS.RECIPE_DESC.DOTA_SWIFT_BLINK = "敏捷跳"
-- 秘奥闪光 OR 智力跳
STRINGS.NAMES.DOTA_ARCANE_BLINK = "秘奥闪光"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_ARCANE_BLINK = "让人精神焕发的工具，可以帮忙分担施展奥术耗费的精力"
STRINGS.RECIPE_DESC.DOTA_ARCANE_BLINK = "智力跳"
-- 盛势闪光 OR 力量跳
STRINGS.NAMES.DOTA_OVERWHELMING_BLINK = "盛势闪光"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_OVERWHELMING_BLINK = "令人生畏的匕首，在混沌之喉中打造，凡人之手几乎无法企及"
STRINGS.RECIPE_DESC.DOTA_OVERWHELMING_BLINK = "力量跳"
-- 鱼叉
STRINGS.NAMES.DOTA_HARPOON = "鱼叉"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_HARPOON = "Null"
STRINGS.RECIPE_DESC.DOTA_HARPOON = "叉鱼"
-------------------------------------------肉山--------------------------------------------------
-- 不朽之守护
STRINGS.NAMES.DOTA_AEGIS_OF_THE_IMMORTAL = "不朽之守护"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_AEGIS_OF_THE_IMMORTAL = "据说不朽者拥有一面能帮他躲过死亡的盾牌"
STRINGS.RECIPE_DESC.DOTA_AEGIS_OF_THE_IMMORTAL = "基础物品"
-- 奶酪
STRINGS.NAMES.DOTA_CHEESE = "奶酪"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_CHEESE = "一个久未谋面的熊怪供应商用奶做的奶酪，能瞬间回复品尝者的活力"
STRINGS.RECIPE_DESC.DOTA_CHEESE = "回血"
-- 刷新球碎片
STRINGS.NAMES.DOTA_REFRESHER_SHARD = "刷新球碎片"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOTA_REFRESHER_SHARD = "无尽之战时代的前前后后，不朽者的求胜之志始终从未动摇"
STRINGS.RECIPE_DESC.DOTA_REFRESHER_SHARD = "重置冷却"

--------------------------------------------------------------------------------------------------
-------------------------------------------动作描述------------------------------------------------
--------------------------------------------------------------------------------------------------
--动作名称
STRINGS.DOTA.NEWACTION = {
	ACTIVATEITEM = "激活",
	WEARDOTAEQUIP = "放至装备栏",
	TAKEOFFDOTAEQUIP = "自装备栏脱下",
	DOTA_TPSCROLL = "传送",
	DOTA_CLARITY = "贴上",
	DOTA_FAERIEFIRE = "吃下",
	DOTA_SMOKE = "散开",
	DOTA_MANGO = "恰",
	DOTA_REGENERATE = "恢复",
	DOTA_TANGO = "吃树",
	DOTA_DUST = "撒粉",
	DOTA_TOME = "阅读",
	DOTA_SALVE = "贴上",
	DOTA_CHOP = "砍伐",
	DOTA_FADING = "渐隐",
	DOTA_MAGICCHARGEPLUS = "充能",
	DOTA_MAGICCHARGE = "充能",
	DOTA_BLINK = "闪烁",
	DOTA_GHOSTFORM = "幽灵形态",
	DOTA_TOGGLE = "切换",
	DOTA_BERSERK = "狂热",
	DOTA_SACRIFICE = "献身",
	DOTA_TRANSMUTE = "炼金",
	DOTA_DOMINATE = "支配",
	DOTA_PHASE = "相位移动",
	DOTA_REPLENISH = "补魔",
	DOTA_BARRIER = "魔法护盾",
	DOTA_RELEASE = "灵魂释放",
	DOTA_RELEASEPLUS = "灵魂释放",
	DOTA_ENDURANCE = "坚韧",
	DOTA_RESTORE = "回复",
	DOTA_ENDURANCEDRUM = "坚韧",
	DOTA_CHARGE = "充能",
	DOTA_MEND = "修复",
	DOTA_VALOR = "无畏",
	DOTA_REPRISAL = "怨灵报复",
	DOTA_CYCLONE = "龙卷风",
	DOTA_CRIPPLE = "致残",
	DOTA_BURST1 = "能量冲击1",
	DOTA_BURST2 = "能量冲击2",
	DOTA_BURST3 = "能量冲击3",
	DOTA_BURST4 = "能量冲击4",
	DOTA_BURST5 = "能量冲击5",
	DOTA_CYCLONEPLUS = "龙卷风",
	DOTA_RESETCOOLDOWNS = "完全重置",
	DOTA_GLIMMER = "微光",
	DOTA_HEX = "妖术",
	DOTA_SHINE = "日耀",
	DOTA_FORCE = "原力",
	DOTA_BURNX = "灵魂燃烧",
	DOTA_GUARD = "坚盾",
	DOTA_AVATAR = "天神下凡",
	DOTA_MIRROR = "镜像",
	DOTA_THRUST = "飓风之力",
	DOTA_SHELL = "回音护盾",
	DOTA_RETURN = "伤害反弹",
	DOTA_INSULATION = "绝缘",
	DOTA_BLAST = "极寒冲击",
	DOTA_BLOODPACT = "血之契约",
	DOTA_SHROUD = "法衣",
	DOTA_WALK = "暗影步",
	DOTA_NULLIFY = "否决",
	DOTA_FLUTTER = "振翅",
	DOTA_BURN = "辉耀灼烧",
	DOTA_UNHOLY = "邪恶之力",
	DOTA_OVERWHELM = "强击",
	DOTA_ETHEREAL = "虚化冲击",
	DOTA_REND = "灵魂撕裂",
	DOTA_PROVINCE = "幻影之域",
	DOTA_DISARM = "缴械",
	DOTA_RAGE = "不洁狂热",
	DOTA_INHIBIT = "阻止",
	DOTA_LIGHTING = "静电冲击",
	DOTA_FONDUE = "干酪",
	DOTA_METEOR = "星陨",
	DOTA_CHAINS = "永恒锁链",
	DOTA_WEAKNESS = "虚弱",
}

-- STRINGS.DOTA.AOEACTION = {

-- }

--------------------------------------------------------------------------------------------------
---------------------------------------------台词-------------------------------------------------
--------------------------------------------------------------------------------------------------

--通用台词
STRINGS.DOTA.SPEECH = {
	COOLDOWN = {
		"冷却中",
		"欲速则不达",
		"还需要时间准备",
		"正在恢复中",
		"冷却中",
		"时机未到",
		"还不是时候",
		"还没准备好",
	},
	NOMANA = {
		"魔法不足",
		"魔力不足",
		"没有足够的魔法",
	},
	NOPOINT = {
		"充能中",
		"没足够的能量点",
	},
}

STRINGS.DOTA.UI_DRAG = "拖拽"
STRINGS.DOTA.LACKMANA = "魔法不足"

--------------------------------------------------------------------------------------------------
-------------------------------------------Buff名称-----------------------------------------------
--------------------------------------------------------------------------------------------------
-- 用于能力勋章
STRINGS.NAMES.BUFF_DOTA_CLARITY = "净化"
STRINGS.NAMES.BUFF_DOTA_SMOKE = "潜行"
STRINGS.NAMES.BUFF_DOTA_DUST = "显形"
STRINGS.NAMES.BUFF_DOTA_DEVOU = "回复"
STRINGS.NAMES.BUFF_DOTA_SALVE = "治疗"
STRINGS.NAMES.BUFF_DOTA_VENOM = "中毒"
STRINGS.NAMES.BUFF_DOTA_BLIGHT = "减甲"
STRINGS.NAMES.BUFF_DOTA_FADING = "渐隐"
STRINGS.NAMES.BUFF_DOTA_BERSERK = "狂热"
STRINGS.NAMES.BUFF_DOTA_CORROSION = "腐蚀"
STRINGS.NAMES.BUFF_DOTA_SACRIFICE = "献身"
STRINGS.NAMES.BUFF_DOTA_PHASE = "相位移动"
STRINGS.NAMES.BUFF_DOTA_RELEASE_POSITIVE = "灵魂释放"
STRINGS.NAMES.BUFF_DOTA_RELEASE_NEGTIVE = "灵魂缠绕"
STRINGS.NAMES.BUFF_DOTA_RELEASEPLUS_POSITIVE = "灵魂释放"
STRINGS.NAMES.BUFF_DOTA_RELEASEPLUS_NEGTIVE = '灵魂缠绕'
STRINGS.NAMES.BUFF_DOTA_ENDURANCE = "坚韧"
STRINGS.NAMES.BUFF_DOTA_ENDURANCEDRUM = "坚韧"
STRINGS.NAMES.BUFF_DOTA_VALOR_POSITIVE = '无畏'
STRINGS.NAMES.BUFF_DOTA_VALOR_NEGTIVE = "畏惧"
STRINGS.NAMES.BUFF_DOTA_GLIMMER = "微光"
STRINGS.NAMES.BUFF_DOTA_BLADE = "巫师之刃"
STRINGS.NAMES.BUFF_DOTA_VALOR_SELF = "日落"
STRINGS.NAMES.BUFF_DOTA_SHINE_NEGTIVE = "日落"
STRINGS.NAMES.BUFF_DOTA_SHINE_POSITIVE = "日耀"
STRINGS.NAMES.BUFF_DOTA_GUARD = "坚盾"
STRINGS.NAMES.BUFF_DOTA_SHELL = "回音护盾"
STRINGS.NAMES.BUFF_DOTA_RETURN = "伤害反弹"
STRINGS.NAMES.BUFF_DOTA_BREAKER = "强断连招"
STRINGS.NAMES.BUFF_DOTA_CORRUPTION = "毁蚀"
STRINGS.NAMES.BUFF_DOTA_WALKPLUS = "暗影步"
STRINGS.NAMES.BUFF_DOTA_WALK = "暗影步"
STRINGS.NAMES.BUFF_DOTA_FLUTTER = "振翅"
STRINGS.NAMES.BUFF_DOTA_SWIFT = "迅疾"
STRINGS.NAMES.BUFF_DOTA_ARCANE = "秘奥"
STRINGS.NAMES.BUFF_DOTA_OVERWHELMING = '盛势'
STRINGS.NAMES.BUFF_DOTA_DISARM = "缴械"
STRINGS.NAMES.BUFF_DOTA_RAGE = "狂热"
STRINGS.NAMES.BUFF_DOTA_INHIBIT = "阻止"
STRINGS.NAMES.BUFF_DOTA_LIGHTING = "静电冲击"
STRINGS.NAMES.BUFF_DOTA_GHOSTFORM = "幽灵形态"
STRINGS.NAMES.BUFF_DOTA_CRIPPLE = "致残"
STRINGS.NAMES.BUFF_DOTA_SKADI = "霜冻"
STRINGS.NAMES.BUFF_DOTA_AVATAR = "天神下凡"
STRINGS.NAMES.BUFF_DOTA_REGENERATE = "恢复"
STRINGS.NAMES.BUFF_DOTA_ETHEREAL = "虚化冲击"
STRINGS.NAMES.BUFF_DOTA_BURN = "灼烧"
STRINGS.NAMES.BUFF_DOTA_CYCLONE = "龙卷风"
STRINGS.NAMES.BUFF_DOTA_CYCLONEPLUS = "龙卷风"
STRINGS.NAMES.BUFF_DOTA_BURNX = "灵魂燃烧"
STRINGS.NAMES.BUFF_DOTA_REND = "灵魂撕裂"
STRINGS.NAMES.BUFF_DOTA_ECHO = "回音一击"
STRINGS.NAMES.BUFF_DOTA_BLOODPACT = '血之契约'
STRINGS.NAMES.BUFF_DOTA_BLOODPACTCD = "血之疲惫"
STRINGS.NAMES.BUFF_DOTA_PROVINCE = "幻影之域"
STRINGS.NAMES.BUFF_DOTA_NULLIFIER = "否决"